name: Deploy Clash Config

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to the GITHUB_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace placeholder with secret URL
        run: |
          ESCAPED_URL=$(printf %s "${CLASH_SUBSCRIPTION_URL}" | sed -e 's/[\/&]/\\&/g')
          sed "s|{{ SECRET_SUBSCRIPTION_URL }}|${ESCAPED_URL}|g" clash_config_template.yaml > clash_config.yaml
        env:
          CLASH_SUBSCRIPTION_URL: ${{ secrets.CLASH_SUBSCRIPTION_URL }}
      - name: Verify generated config
        run: |
          cat clash_config.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: .
          force_orphan: true
          enable_jekyll: false
          keep_files: false
          publish_branch: gh-pages
